title: Alex
logo:  #/assets/img/logo.png
description: Public Projects
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

collections:
  projects:
    defaults:
      layout: project
    output: true
    permalink: /project/:path/